defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

experiment:
  name: VAE_Experiment
  epochs: 30
  batch_size: 128
  learning_rate: 1e-3
  latent_dim: 32
  encoder_hidden_dims: [256,128]
  decoder_hidden_dims: [128,256]
  data_type: "bernoulli"
  beta: 1.0
  dropout_rate: 0.1
  device: "cuda"

wandb:
  project: "vae-image-generation"
  mode: online

hydra:
  run:
    dir: output/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
